language: php

jobs:
  include:
    - php: 7.1
    - php: 7.1
      env: deps=low
    - php: 7.2
    - php: 7.2
      env: deps=low
    - php: 7.3
    - php: 7.3
      env: deps=low
    - php: 7.4
    - php: 7.4
      env: deps=low
    - php: nightly
      env: deps=low
    - php: nightly
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction
  - if [[ $deps = low ]]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction; fi

script:
  - composer validate
  - composer grumphp

after_success:
  - phpenv config-rm xdebug.ini
  - composer scrutinizer
