language: php

sudo: false

matrix:
    include:
        - php: 5.6
        - php: 5.6
          env: deps=low
        - php: 7.0
        - php: 7.1

cache:
    directories:
        - $HOME/.composer/cache/files

install:
    - travis_retry composer install

before_script:
    - if [[ $deps = low ]]; then composer update --prefer-lowest --prefer-stable; fi

script: ./vendor/bin/phpspec run
