language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

script:
  - composer validate
  - composer update
  - bin/phpspec run --no-code-generation

cache:
  directories:
    - $HOME/.composer/cache/files

install:
    - travis_retry composer install

