language: php
matrix:
  include:
    - php: 7.1
    - php: 7.1
      env: deps=low
    - php: 7.2
    - php: 7.2
      env: deps=low


cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
    - if [[ $deps = low ]]; then composer update --prefer-lowest --prefer-stable; fi

script:
  - composer validate
  - composer update
  - bin/phpspec run --no-code-generation

install:
    - travis_retry composer install


